import { spawn } from "node:child_process";
import { readFile, stat } from "node:fs/promises";
import { basename, join, relative } from "node:path";
import type { GatherContext, SizeStatsEvidence, SizeStatsFile } from "../../sdk/types.js";
import { countLines } from "../../util/count-lines.js";
import { exec } from "../../util/exec.js";

const SIZE_PROBE_LIMIT = 5000;
const BYTE_THRESHOLD_FOR_LINE_COUNT = 2 * 1024 * 1024;

/**
 * Filenames we treat as generated by default, even without a `.gitattributes`
 * `linguist-generated=true` entry. These are package-manager / build-tool
 * lockfiles that a repo *must* commit but no agent should ever read end-to-end.
 * Counting them as "agent context cost" punishes repos for doing the right
 * thing.
 */
const DEFAULT_GENERATED_FILENAMES = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "npm-shrinkwrap.json",
  "bun.lockb",
  "bun.lock",
  "Cargo.lock",
  "Gemfile.lock",
  "composer.lock",
  "poetry.lock",
  "Pipfile.lock",
  "go.sum",
  "flake.lock",
  "mix.lock",
  "pubspec.lock",
]);

export const sizeStatsSubsystem = {
  async gather(ctx: GatherContext): Promise<SizeStatsEvidence> {
    const paths = await listTrackedFiles(ctx.cwd);
    if (paths === null) return empty("none");

    const sliced = paths.slice(0, SIZE_PROBE_LIMIT);
    const linguistGenerated = await readLinguistGenerated(ctx.cwd, sliced);
    const entries = await Promise.all(
      sliced.map((p) => describeFile(ctx.cwd, p, linguistGenerated)),
    );
    const files = entries.filter((e): e is SizeStatsFile => e !== null);

    let totalBytes = 0;
    let totalBytesEffective = 0;
    let totalFilesEffective = 0;
    for (const f of files) {
      totalBytes += f.bytes;
      if (!f.generated) {
        totalBytesEffective += f.bytes;
        totalFilesEffective += 1;
      }
    }

    return {
      files,
      totalBytes,
      totalFiles: files.length,
      totalBytesEffective,
      totalFilesEffective,
      source: "git-ls-files",
    };
  },
};

async function listTrackedFiles(cwd: string): Promise<string[] | null> {
  try {
    const { stdout } = await exec("git", ["ls-files", "-z"], { cwd, maxBuffer: 32 * 1024 * 1024 });
    return stdout
      .split("\0")
      .map((p) => p.trim())
      .filter((p) => p.length > 0);
  } catch {
    return null;
  }
}

/**
 * Returns the subset of `paths` that git reports as `linguist-generated=true`
 * via `git check-attr`. We pass paths over stdin to dodge ARG_MAX.
 */
async function readLinguistGenerated(cwd: string, paths: string[]): Promise<Set<string>> {
  const out = new Set<string>();
  if (paths.length === 0) return out;
  const stdout = await runCheckAttr(cwd, paths);
  if (stdout === null) return out;
  // git check-attr -z output: path \0 attr \0 value \0 path \0 attr \0 value \0 ...
  const parts = stdout.split("\0");
  for (let i = 0; i + 2 < parts.length; i += 3) {
    const path = parts[i];
    const value = parts[i + 2];
    if (path && value === "true") out.add(path);
  }
  return out;
}

function runCheckAttr(cwd: string, paths: string[]): Promise<string | null> {
  return new Promise((resolve) => {
    let child: ReturnType<typeof spawn>;
    try {
      child = spawn("git", ["check-attr", "--stdin", "-z", "linguist-generated"], {
        cwd,
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch {
      resolve(null);
      return;
    }
    let stdout = "";
    let resolved = false;
    const done = (v: string | null) => {
      if (resolved) return;
      resolved = true;
      resolve(v);
    };
    child.stdout?.on("data", (chunk) => {
      stdout += chunk.toString("utf8");
    });
    child.on("error", () => done(null));
    child.on("close", (code) => done(code === 0 ? stdout : null));
    child.stdin?.on("error", () => done(null));
    // git check-attr -z --stdin: input paths are NUL-separated when -z is set.
    child.stdin?.end(`${paths.join("\0")}\0`);
  });
}

async function describeFile(
  cwd: string,
  path: string,
  linguistGenerated: Set<string>,
): Promise<SizeStatsFile | null> {
  const abs = join(cwd, path);
  let bytes: number;
  try {
    const s = await stat(abs);
    if (!s.isFile()) return null;
    bytes = s.size;
  } catch {
    return null;
  }

  let lines = 0;
  if (bytes > 0 && bytes < BYTE_THRESHOLD_FOR_LINE_COUNT) {
    try {
      const text = await readFile(abs, "utf8");
      lines = countLines(text);
    } catch {
      lines = 0;
    }
  }

  const rel = relative(cwd, abs);
  const finalPath = rel || path;
  const generated =
    linguistGenerated.has(finalPath) ||
    linguistGenerated.has(path) ||
    DEFAULT_GENERATED_FILENAMES.has(basename(finalPath));

  return {
    path: finalPath,
    bytes,
    lines,
    depth: rel.split("/").length,
    generated,
  };
}

function empty(source: SizeStatsEvidence["source"]): SizeStatsEvidence {
  return {
    files: [],
    totalBytes: 0,
    totalFiles: 0,
    totalBytesEffective: 0,
    totalFilesEffective: 0,
    source,
  };
}
