import type { InventoryItem } from "@esbenwiberg/repofit/sdk";
import { defineProbe } from "@esbenwiberg/repofit/sdk";

const SOURCE_OR_SCHEMA =
  /\.(?:ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|kt|cs|json|ya?ml|graphql|proto)$/i;
const GENERATED_PATH =
  /(?:^|\/)(?:generated|__generated__|gen|autogen|openapi-client|graphql\/generated)(?:\/|$)|(?:^|\/)[^/]+\.(?:gen|generated|pb)\.[^.]+$/i;
const GENERATED_HEADER =
  /^\s*(?:\/\/|\/\*|\*|#|<!--)\s*(?:@generated|code generated|.*do not edit|auto-generated)/im;
const SKIP_DIRS = /(?:^|\/)(?:node_modules|coverage|\.git)\//;
const TEST_OR_FIXTURE_PATH =
  /(?:\.test\.|\.spec\.|__tests__|^tests?\/|\/tests?\/|^fixtures\/|\/fixtures\/|^examples\/|\/examples\/)/i;

export default defineProbe({
  id: "generated.code-marked",
  version: "1.0.0",
  dimensions: [
    { id: "context", weight: 0.5 },
    { id: "cost", weight: 1 },
    { id: "consistency", weight: 0.5 },
  ],
  tier: "static",
  evidence: ["files", "size_stats"],

  rationale: `
    Generated code is often necessary, but agents should know not to edit it
    as source. The size subsystem already respects files marked
    linguist-generated. This probe flags tracked files that look generated by
    path or header but are not marked generated.
  `,

  remediation:
    "Mark generated files in `.gitattributes` with `linguist-generated=true`, keep generated code under a clear directory, and document the source command that regenerates it. Agents should patch the source schema/template, not the artifact.",

  async detect(ev) {
    const candidates = ev.size_stats.files
      .filter((f) => !f.generated)
      .filter(
        (f) =>
          SOURCE_OR_SCHEMA.test(f.path) &&
          !SKIP_DIRS.test(`/${f.path}`) &&
          !TEST_OR_FIXTURE_PATH.test(f.path),
      )
      .sort((a, b) => a.path.localeCompare(b.path));

    const items: InventoryItem[] = [];
    for (const f of candidates) {
      let looksGenerated = GENERATED_PATH.test(f.path);
      if (!looksGenerated && f.bytes < 100_000) {
        const text = await ev.files.readText(f.path);
        const head = text?.slice(0, 1_000) ?? "";
        looksGenerated = GENERATED_HEADER.test(head);
      }
      if (looksGenerated) {
        items.push({
          location: { path: f.path },
          severity: "warn",
          message: "looks generated but is not marked generated",
        });
      }
    }

    return { kind: "inventory", items };
  },

  score: {
    kind: "inventory",
    severityWeights: { info: 1, warn: 3, error: 10 },
    bands: [{ upTo: 0, score: 100 }, { upTo: 3, score: 80 }, { upTo: 9, score: 50 }, { score: 0 }],
  },

  fixtures: [
    {
      name: "no-generated-looking-files",
      evidence: {
        files: { "src/index.ts": "export const ok = true;\n" },
        size_stats: {
          source: "git-ls-files",
          totalBytes: 100,
          totalFiles: 1,
          files: [{ path: "src/index.ts", bytes: 100, lines: 1, depth: 1 }],
        },
      },
      expect: { reading: { kind: "inventory", items: [] }, score: 100 },
    },
    {
      name: "marked-generated-is-ok",
      evidence: {
        files: { "src/generated/client.ts": "// Code generated by OpenAPI. DO NOT EDIT.\n" },
        size_stats: {
          source: "git-ls-files",
          totalBytes: 100,
          totalFiles: 1,
          files: [
            { path: "src/generated/client.ts", bytes: 100, lines: 1, depth: 2, generated: true },
          ],
        },
      },
      expect: { reading: { kind: "inventory", items: [] }, score: 100 },
    },
    {
      name: "unmarked-generated",
      evidence: {
        files: { "src/generated/client.ts": "// Code generated by OpenAPI. DO NOT EDIT.\n" },
        size_stats: {
          source: "git-ls-files",
          totalBytes: 100,
          totalFiles: 1,
          files: [{ path: "src/generated/client.ts", bytes: 100, lines: 1, depth: 2 }],
        },
      },
      expect: {
        reading: {
          kind: "inventory",
          items: [
            {
              location: { path: "src/generated/client.ts" },
              severity: "warn",
              message: "looks generated but is not marked generated",
            },
          ],
        },
        score: 80,
      },
    },
  ],
});
