export { type FixtureOutcome, runFixture } from "../fixtures/runner.js";
export { defineDimension } from "./define-dimension.js";
export { defineFixer } from "./define-fixer.js";
export { defineProbe } from "./define-probe.js";
export { defineReporter } from "./define-reporter.js";
export type {
  AgentConfigEvidence,
  Band,
  CentralPackagesInfo,
  DimensionAssignment,
  DimensionOverride,
  DimensionRecipe,
  DotnetProjectEvidence,
  DotnetProjectInfo,
  EvidenceMap,
  FilesEvidence,
  FixAction,
  FixActionAppendLines,
  FixActionWriteFile,
  FixContext,
  Fixer,
  FixPlan,
  Fixture,
  FixtureExpect,
  GatherContext,
  Generate,
  GenerateOptions,
  GitignoreEvidence,
  GoModuleEvidence,
  GoModuleInfo,
  GuidanceFile,
  InventoryItem,
  LlmFixContext,
  LlmFixer,
  Location,
  NodePackageEvidence,
  Probe,
  PyProjectInfo,
  PythonProjectEvidence,
  Reading,
  Reporter,
  ReporterContext,
  ScoreConfig,
  Severity,
  StaticFixer,
  Tier,
  ToolchainCommand,
  ToolchainContext,
  ToolchainEvidence,
  ToolchainPhase,
  ToolchainStack,
} from "./types.js";
